package server

import (
	"testing"
)

func Test_Accepted(t *testing.T) { runGalaTest(t, TestAccepted) }
func Test_AuthAllowsWithHeader(t *testing.T) { runGalaTest(t, TestAuthAllowsWithHeader) }
func Test_AuthBearerAcceptsValidToken(t *testing.T) { runGalaTest(t, TestAuthBearerAcceptsValidToken) }
func Test_AuthBearerCreation(t *testing.T) { runGalaTest(t, TestAuthBearerCreation) }
func Test_AuthBearerRejectsInvalidToken(t *testing.T) { runGalaTest(t, TestAuthBearerRejectsInvalidToken) }
func Test_AuthBearerRejectsMissingBearer(t *testing.T) { runGalaTest(t, TestAuthBearerRejectsMissingBearer) }
func Test_AuthBearerRejectsNoHeader(t *testing.T) { runGalaTest(t, TestAuthBearerRejectsNoHeader) }
func Test_AuthCreation(t *testing.T) { runGalaTest(t, TestAuthCreation) }
func Test_AuthRejectsWithoutHeader(t *testing.T) { runGalaTest(t, TestAuthRejectsWithoutHeader) }
func Test_AuthWithValidatorAcceptsValid(t *testing.T) { runGalaTest(t, TestAuthWithValidatorAcceptsValid) }
func Test_AuthWithValidatorCreation(t *testing.T) { runGalaTest(t, TestAuthWithValidatorCreation) }
func Test_AuthWithValidatorRejectsInvalid(t *testing.T) { runGalaTest(t, TestAuthWithValidatorRejectsInvalid) }
func Test_BadGatewayResponse(t *testing.T) { runGalaTest(t, TestBadGatewayResponse) }
func Test_BadRequest(t *testing.T) { runGalaTest(t, TestBadRequest) }
func Test_BasicAuthAcceptsValidCredentials(t *testing.T) { runGalaTest(t, TestBasicAuthAcceptsValidCredentials) }
func Test_BasicAuthCreation(t *testing.T) { runGalaTest(t, TestBasicAuthCreation) }
func Test_BasicAuthRejectsInvalidCredentials(t *testing.T) { runGalaTest(t, TestBasicAuthRejectsInvalidCredentials) }
func Test_BasicAuthRejectsMissingHeader(t *testing.T) { runGalaTest(t, TestBasicAuthRejectsMissingHeader) }
func Test_BasicAuthSetsUsernameInContext(t *testing.T) { runGalaTest(t, TestBasicAuthSetsUsernameInContext) }
func Test_BodyDumpCapturesBodies(t *testing.T) { runGalaTest(t, TestBodyDumpCapturesBodies) }
func Test_BodyDumpCreation(t *testing.T) { runGalaTest(t, TestBodyDumpCreation) }
func Test_BodyDumpDoesNotAlterResponse(t *testing.T) { runGalaTest(t, TestBodyDumpDoesNotAlterResponse) }
func Test_BodyLimitAllowsSmallBody(t *testing.T) { runGalaTest(t, TestBodyLimitAllowsSmallBody) }
func Test_BodyLimitBytesCreation(t *testing.T) { runGalaTest(t, TestBodyLimitBytesCreation) }
func Test_BodyLimitBytesExactBoundary(t *testing.T) { runGalaTest(t, TestBodyLimitBytesExactBoundary) }
func Test_BodyLimitCreation(t *testing.T) { runGalaTest(t, TestBodyLimitCreation) }
func Test_BodyLimitParsesUnits(t *testing.T) { runGalaTest(t, TestBodyLimitParsesUnits) }
func Test_BodyLimitRejectsLargeBody(t *testing.T) { runGalaTest(t, TestBodyLimitRejectsLargeBody) }
func Test_CSRFAcceptsPOSTWithValidToken(t *testing.T) { runGalaTest(t, TestCSRFAcceptsPOSTWithValidToken) }
func Test_CSRFCreation(t *testing.T) { runGalaTest(t, TestCSRFCreation) }
func Test_CSRFRejectsPOSTWithoutToken(t *testing.T) { runGalaTest(t, TestCSRFRejectsPOSTWithoutToken) }
func Test_CSRFSetsCookieOnGET(t *testing.T) { runGalaTest(t, TestCSRFSetsCookieOnGET) }
func Test_CSRFSkipsGET(t *testing.T) { runGalaTest(t, TestCSRFSkipsGET) }
func Test_CSRFSkipsHEAD(t *testing.T) { runGalaTest(t, TestCSRFSkipsHEAD) }
func Test_CSRFSkipsOPTIONS(t *testing.T) { runGalaTest(t, TestCSRFSkipsOPTIONS) }
func Test_ConfigPreservedAcrossBuilderCalls(t *testing.T) { runGalaTest(t, TestConfigPreservedAcrossBuilderCalls) }
func Test_Conflict(t *testing.T) { runGalaTest(t, TestConflict) }
func Test_CookieImmutability(t *testing.T) { runGalaTest(t, TestCookieImmutability) }
func Test_CorsAddsHeaders(t *testing.T) { runGalaTest(t, TestCorsAddsHeaders) }
func Test_CorsCreation(t *testing.T) { runGalaTest(t, TestCorsCreation) }
func Test_CorsOptionsPreflightReturns204(t *testing.T) { runGalaTest(t, TestCorsOptionsPreflightReturns204) }
func Test_CorsWithConfigCreation(t *testing.T) { runGalaTest(t, TestCorsWithConfigCreation) }
func Test_CorsWithConfigCustom(t *testing.T) { runGalaTest(t, TestCorsWithConfigCustom) }
func Test_CorsWithCustomOrigin(t *testing.T) { runGalaTest(t, TestCorsWithCustomOrigin) }
func Test_CorsWithOriginsCreation(t *testing.T) { runGalaTest(t, TestCorsWithOriginsCreation) }
func Test_CreateAndParseJWT(t *testing.T) { runGalaTest(t, TestCreateAndParseJWT) }
func Test_Created(t *testing.T) { runGalaTest(t, TestCreated) }
func Test_CustomStatusCode(t *testing.T) { runGalaTest(t, TestCustomStatusCode) }
func Test_DecompressCreation(t *testing.T) { runGalaTest(t, TestDecompressCreation) }
func Test_FilterImmutability(t *testing.T) { runGalaTest(t, TestFilterImmutability) }
func Test_FilterPreservesResponseBody(t *testing.T) { runGalaTest(t, TestFilterPreservesResponseBody) }
func Test_Forbidden(t *testing.T) { runGalaTest(t, TestForbidden) }
func Test_FullFrameworkConfiguration(t *testing.T) { runGalaTest(t, TestFullFrameworkConfiguration) }
func Test_Group(t *testing.T) { runGalaTest(t, TestGroup) }
func Test_GroupFilters(t *testing.T) { runGalaTest(t, TestGroupFilters) }
func Test_GroupFiltersDoNotLeakToParent(t *testing.T) { runGalaTest(t, TestGroupFiltersDoNotLeakToParent) }
func Test_GroupMultipleGroups(t *testing.T) { runGalaTest(t, TestGroupMultipleGroups) }
func Test_GroupPreservesExistingRoutes(t *testing.T) { runGalaTest(t, TestGroupPreservesExistingRoutes) }
func Test_GzipAddsHeadersWhenAccepted(t *testing.T) { runGalaTest(t, TestGzipAddsHeadersWhenAccepted) }
func Test_GzipCreation(t *testing.T) { runGalaTest(t, TestGzipCreation) }
func Test_GzipSkipsEmptyBody(t *testing.T) { runGalaTest(t, TestGzipSkipsEmptyBody) }
func Test_GzipSkipsWhenNotAccepted(t *testing.T) { runGalaTest(t, TestGzipSkipsWhenNotAccepted) }
func Test_HTMLBlobResponse(t *testing.T) { runGalaTest(t, TestHTMLBlobResponse) }
func Test_HTMLBlobWithStatusResponse(t *testing.T) { runGalaTest(t, TestHTMLBlobWithStatusResponse) }
func Test_HTTPErrorInFilter(t *testing.T) { runGalaTest(t, TestHTTPErrorInFilter) }
func Test_HTTPErrorNewHTTPError(t *testing.T) { runGalaTest(t, TestHTTPErrorNewHTTPError) }
func Test_HTTPErrorString(t *testing.T) { runGalaTest(t, TestHTTPErrorString) }
func Test_HTTPErrorToJsonResponse(t *testing.T) { runGalaTest(t, TestHTTPErrorToJsonResponse) }
func Test_HTTPErrorToResponse(t *testing.T) { runGalaTest(t, TestHTTPErrorToResponse) }
func Test_HTTPErrorWithInternal(t *testing.T) { runGalaTest(t, TestHTTPErrorWithInternal) }
func Test_HTTPSRedirectCreation(t *testing.T) { runGalaTest(t, TestHTTPSRedirectCreation) }
func Test_HTTPSRedirectOnHTTP(t *testing.T) { runGalaTest(t, TestHTTPSRedirectOnHTTP) }
func Test_HTTPSRedirectPreservesQuery(t *testing.T) { runGalaTest(t, TestHTTPSRedirectPreservesQuery) }
func Test_HTTPSRedirectSkipsHTTPS(t *testing.T) { runGalaTest(t, TestHTTPSRedirectSkipsHTTPS) }
func Test_HeaderValueNotFound(t *testing.T) { runGalaTest(t, TestHeaderValueNotFound) }
func Test_Html(t *testing.T) { runGalaTest(t, TestHtml) }
func Test_IntegrationAuthFilter(t *testing.T) { runGalaTest(t, TestIntegrationAuthFilter) }
func Test_IntegrationBasicGET(t *testing.T) { runGalaTest(t, TestIntegrationBasicGET) }
func Test_IntegrationContentTypes(t *testing.T) { runGalaTest(t, TestIntegrationContentTypes) }
func Test_IntegrationCookies(t *testing.T) { runGalaTest(t, TestIntegrationCookies) }
func Test_IntegrationCorsFilter(t *testing.T) { runGalaTest(t, TestIntegrationCorsFilter) }
func Test_IntegrationCustomErrorHandler(t *testing.T) { runGalaTest(t, TestIntegrationCustomErrorHandler) }
func Test_IntegrationGroupRoutes(t *testing.T) { runGalaTest(t, TestIntegrationGroupRoutes) }
func Test_IntegrationLoggerFilter(t *testing.T) { runGalaTest(t, TestIntegrationLoggerFilter) }
func Test_IntegrationPOSTBody(t *testing.T) { runGalaTest(t, TestIntegrationPOSTBody) }
func Test_IntegrationPathParams(t *testing.T) { runGalaTest(t, TestIntegrationPathParams) }
func Test_IntegrationQueryParams(t *testing.T) { runGalaTest(t, TestIntegrationQueryParams) }
func Test_IntegrationRecoveryFilter(t *testing.T) { runGalaTest(t, TestIntegrationRecoveryFilter) }
func Test_IntegrationRequestContext(t *testing.T) { runGalaTest(t, TestIntegrationRequestContext) }
func Test_IntegrationResponseHeaders(t *testing.T) { runGalaTest(t, TestIntegrationResponseHeaders) }
func Test_InternalError(t *testing.T) { runGalaTest(t, TestInternalError) }
func Test_JSONBlobResponse(t *testing.T) { runGalaTest(t, TestJSONBlobResponse) }
func Test_JSONBlobWithStatusResponse(t *testing.T) { runGalaTest(t, TestJSONBlobWithStatusResponse) }
func Test_JSONPResponse(t *testing.T) { runGalaTest(t, TestJSONPResponse) }
func Test_JSONPWithStatusResponse(t *testing.T) { runGalaTest(t, TestJSONPWithStatusResponse) }
func Test_JWTAuthAcceptsValidToken(t *testing.T) { runGalaTest(t, TestJWTAuthAcceptsValidToken) }
func Test_JWTAuthCreation(t *testing.T) { runGalaTest(t, TestJWTAuthCreation) }
func Test_JWTAuthRejectsExpiredToken(t *testing.T) { runGalaTest(t, TestJWTAuthRejectsExpiredToken) }
func Test_JWTAuthRejectsInvalidSignature(t *testing.T) { runGalaTest(t, TestJWTAuthRejectsInvalidSignature) }
func Test_JWTAuthRejectsMalformedToken(t *testing.T) { runGalaTest(t, TestJWTAuthRejectsMalformedToken) }
func Test_JWTAuthRejectsMissingToken(t *testing.T) { runGalaTest(t, TestJWTAuthRejectsMissingToken) }
func Test_JWTAuthRejectsNonBearerHeader(t *testing.T) { runGalaTest(t, TestJWTAuthRejectsNonBearerHeader) }
func Test_JWTAuthStoresClaimsInContext(t *testing.T) { runGalaTest(t, TestJWTAuthStoresClaimsInContext) }
func Test_JWTAuthWithConfigCreation(t *testing.T) { runGalaTest(t, TestJWTAuthWithConfigCreation) }
func Test_JWTAuthWithConfigSkipsExpiryCheck(t *testing.T) { runGalaTest(t, TestJWTAuthWithConfigSkipsExpiryCheck) }
func Test_JWTNumericClaims(t *testing.T) { runGalaTest(t, TestJWTNumericClaims) }
func Test_JWTRejectsMalformed(t *testing.T) { runGalaTest(t, TestJWTRejectsMalformed) }
func Test_JWTRejectsWrongSecret(t *testing.T) { runGalaTest(t, TestJWTRejectsWrongSecret) }
func Test_JsonResponse(t *testing.T) { runGalaTest(t, TestJsonResponse) }
func Test_JsonWithStatus(t *testing.T) { runGalaTest(t, TestJsonWithStatus) }
func Test_KeyAuthCookieAcceptsValidKey(t *testing.T) { runGalaTest(t, TestKeyAuthCookieAcceptsValidKey) }
func Test_KeyAuthCreation(t *testing.T) { runGalaTest(t, TestKeyAuthCreation) }
func Test_KeyAuthHeaderAcceptsValidKey(t *testing.T) { runGalaTest(t, TestKeyAuthHeaderAcceptsValidKey) }
func Test_KeyAuthHeaderRejectsInvalidKey(t *testing.T) { runGalaTest(t, TestKeyAuthHeaderRejectsInvalidKey) }
func Test_KeyAuthQueryAcceptsValidKey(t *testing.T) { runGalaTest(t, TestKeyAuthQueryAcceptsValidKey) }
func Test_KeyAuthRejectsMissingKey(t *testing.T) { runGalaTest(t, TestKeyAuthRejectsMissingKey) }
func Test_LoggerCreation(t *testing.T) { runGalaTest(t, TestLoggerCreation) }
func Test_LoggerDoesNotAlterResponse(t *testing.T) { runGalaTest(t, TestLoggerDoesNotAlterResponse) }
func Test_LoggerWithFormatDoesNotAlterResponse(t *testing.T) { runGalaTest(t, TestLoggerWithFormatDoesNotAlterResponse) }
func Test_MethodNotAllowed(t *testing.T) { runGalaTest(t, TestMethodNotAllowed) }
func Test_MethodOverrideCreation(t *testing.T) { runGalaTest(t, TestMethodOverrideCreation) }
func Test_MethodOverrideFromFormField(t *testing.T) { runGalaTest(t, TestMethodOverrideFromFormField) }
func Test_MethodOverrideFromHeader(t *testing.T) { runGalaTest(t, TestMethodOverrideFromHeader) }
func Test_MethodOverridePassesThroughWithoutOverride(t *testing.T) { runGalaTest(t, TestMethodOverridePassesThroughWithoutOverride) }
func Test_MethodOverrideSkipsGET(t *testing.T) { runGalaTest(t, TestMethodOverrideSkipsGET) }
func Test_MethodSealed(t *testing.T) { runGalaTest(t, TestMethodSealed) }
func Test_MultipleFiltersCompose(t *testing.T) { runGalaTest(t, TestMultipleFiltersCompose) }
func Test_NestedGroups(t *testing.T) { runGalaTest(t, TestNestedGroups) }
func Test_NewGroup(t *testing.T) { runGalaTest(t, TestNewGroup) }
func Test_NewServer(t *testing.T) { runGalaTest(t, TestNewServer) }
func Test_NoContent(t *testing.T) { runGalaTest(t, TestNoContent) }
func Test_NonWWWRedirectCreation(t *testing.T) { runGalaTest(t, TestNonWWWRedirectCreation) }
func Test_NonWWWRedirectRemovesWWW(t *testing.T) { runGalaTest(t, TestNonWWWRedirectRemovesWWW) }
func Test_NonWWWRedirectSkipsNonWWW(t *testing.T) { runGalaTest(t, TestNonWWWRedirectSkipsNonWWW) }
func Test_NotFound(t *testing.T) { runGalaTest(t, TestNotFound) }
func Test_Ok(t *testing.T) { runGalaTest(t, TestOk) }
func Test_ProxyCreation(t *testing.T) { runGalaTest(t, TestProxyCreation) }
func Test_ProxyWithTimeoutCreation(t *testing.T) { runGalaTest(t, TestProxyWithTimeoutCreation) }
func Test_RateLimitAllowsRequests(t *testing.T) { runGalaTest(t, TestRateLimitAllowsRequests) }
func Test_RateLimitCreation(t *testing.T) { runGalaTest(t, TestRateLimitCreation) }
func Test_RateLimitPerIPAllowsDifferentIPs(t *testing.T) { runGalaTest(t, TestRateLimitPerIPAllowsDifferentIPs) }
func Test_RateLimitPerIPCreation(t *testing.T) { runGalaTest(t, TestRateLimitPerIPCreation) }
func Test_RateLimitRejectsWhenExhausted(t *testing.T) { runGalaTest(t, TestRateLimitRejectsWhenExhausted) }
func Test_RecoveryCreation(t *testing.T) { runGalaTest(t, TestRecoveryCreation) }
func Test_RecoveryPassesThroughOnSuccess(t *testing.T) { runGalaTest(t, TestRecoveryPassesThroughOnSuccess) }
func Test_RecoveryReturns500OnPanic(t *testing.T) { runGalaTest(t, TestRecoveryReturns500OnPanic) }
func Test_Redirect(t *testing.T) { runGalaTest(t, TestRedirect) }
func Test_RedirectPermanent(t *testing.T) { runGalaTest(t, TestRedirectPermanent) }
func Test_RemoveTrailingSlashCreation(t *testing.T) { runGalaTest(t, TestRemoveTrailingSlashCreation) }
func Test_RemoveTrailingSlashRemoves(t *testing.T) { runGalaTest(t, TestRemoveTrailingSlashRemoves) }
func Test_RemoveTrailingSlashSkipsNoSlash(t *testing.T) { runGalaTest(t, TestRemoveTrailingSlashSkipsNoSlash) }
func Test_RemoveTrailingSlashSkipsRoot(t *testing.T) { runGalaTest(t, TestRemoveTrailingSlashSkipsRoot) }
func Test_RequestBody(t *testing.T) { runGalaTest(t, TestRequestBody) }
func Test_RequestContentType(t *testing.T) { runGalaTest(t, TestRequestContentType) }
func Test_RequestCookie(t *testing.T) { runGalaTest(t, TestRequestCookie) }
func Test_RequestCtxGetMissing(t *testing.T) { runGalaTest(t, TestRequestCtxGetMissing) }
func Test_RequestCtxGetSet(t *testing.T) { runGalaTest(t, TestRequestCtxGetSet) }
func Test_RequestFormValue(t *testing.T) { runGalaTest(t, TestRequestFormValue) }
func Test_RequestHeader(t *testing.T) { runGalaTest(t, TestRequestHeader) }
func Test_RequestHost(t *testing.T) { runGalaTest(t, TestRequestHost) }
func Test_RequestIdAddsHeader(t *testing.T) { runGalaTest(t, TestRequestIdAddsHeader) }
func Test_RequestIdCreation(t *testing.T) { runGalaTest(t, TestRequestIdCreation) }
func Test_RequestIdIncrementsCounter(t *testing.T) { runGalaTest(t, TestRequestIdIncrementsCounter) }
func Test_RequestIdSetsContext(t *testing.T) { runGalaTest(t, TestRequestIdSetsContext) }
func Test_RequestIsTLS(t *testing.T) { runGalaTest(t, TestRequestIsTLS) }
func Test_RequestMethod(t *testing.T) { runGalaTest(t, TestRequestMethod) }
func Test_RequestParam(t *testing.T) { runGalaTest(t, TestRequestParam) }
func Test_RequestParamInt(t *testing.T) { runGalaTest(t, TestRequestParamInt) }
func Test_RequestPath(t *testing.T) { runGalaTest(t, TestRequestPath) }
func Test_RequestQueryParam(t *testing.T) { runGalaTest(t, TestRequestQueryParam) }
func Test_RequestQueryParamDefault(t *testing.T) { runGalaTest(t, TestRequestQueryParamDefault) }
func Test_RequestQueryParamInt(t *testing.T) { runGalaTest(t, TestRequestQueryParamInt) }
func Test_RequestRealIP(t *testing.T) { runGalaTest(t, TestRequestRealIP) }
func Test_RequestRealIPFallback(t *testing.T) { runGalaTest(t, TestRequestRealIPFallback) }
func Test_RequestScheme(t *testing.T) { runGalaTest(t, TestRequestScheme) }
func Test_RequestTimeout(t *testing.T) { runGalaTest(t, TestRequestTimeout) }
func Test_ResponseChaining(t *testing.T) { runGalaTest(t, TestResponseChaining) }
func Test_ResponseDeleteCookie(t *testing.T) { runGalaTest(t, TestResponseDeleteCookie) }
func Test_ResponseImmutability(t *testing.T) { runGalaTest(t, TestResponseImmutability) }
func Test_ResponseMultipleCookies(t *testing.T) { runGalaTest(t, TestResponseMultipleCookies) }
func Test_ResponseSetCookie(t *testing.T) { runGalaTest(t, TestResponseSetCookie) }
func Test_ResponseSetSecureCookie(t *testing.T) { runGalaTest(t, TestResponseSetSecureCookie) }
func Test_ResponseWithBody(t *testing.T) { runGalaTest(t, TestResponseWithBody) }
func Test_ResponseWithHeader(t *testing.T) { runGalaTest(t, TestResponseWithHeader) }
func Test_ResponseWithStatus(t *testing.T) { runGalaTest(t, TestResponseWithStatus) }
func Test_RewriteCreation(t *testing.T) { runGalaTest(t, TestRewriteCreation) }
func Test_RewriteMatchingRule(t *testing.T) { runGalaTest(t, TestRewriteMatchingRule) }
func Test_RewriteMultipleRules(t *testing.T) { runGalaTest(t, TestRewriteMultipleRules) }
func Test_RewriteNoMatch(t *testing.T) { runGalaTest(t, TestRewriteNoMatch) }
func Test_RouteFilter(t *testing.T) { runGalaTest(t, TestRouteFilter) }
func Test_RouteMultipleFilters(t *testing.T) { runGalaTest(t, TestRouteMultipleFilters) }
func Test_SecureAddsDefaultHeaders(t *testing.T) { runGalaTest(t, TestSecureAddsDefaultHeaders) }
func Test_SecureCreation(t *testing.T) { runGalaTest(t, TestSecureCreation) }
func Test_SecureSkipsEmptyValues(t *testing.T) { runGalaTest(t, TestSecureSkipsEmptyValues) }
func Test_SecureWithConfigCustomHeaders(t *testing.T) { runGalaTest(t, TestSecureWithConfigCustomHeaders) }
func Test_ServerAllMethods(t *testing.T) { runGalaTest(t, TestServerAllMethods) }
func Test_ServerAnyMethod(t *testing.T) { runGalaTest(t, TestServerAnyMethod) }
func Test_ServerGET(t *testing.T) { runGalaTest(t, TestServerGET) }
func Test_ServerImmutability(t *testing.T) { runGalaTest(t, TestServerImmutability) }
func Test_ServerMultipleRoutes(t *testing.T) { runGalaTest(t, TestServerMultipleRoutes) }
func Test_ServerNamed(t *testing.T) { runGalaTest(t, TestServerNamed) }
func Test_ServerRenderWithoutRenderer(t *testing.T) { runGalaTest(t, TestServerRenderWithoutRenderer) }
func Test_ServerRoutesDebug(t *testing.T) { runGalaTest(t, TestServerRoutesDebug) }
func Test_ServerURLGeneration(t *testing.T) { runGalaTest(t, TestServerURLGeneration) }
func Test_ServiceUnavailable(t *testing.T) { runGalaTest(t, TestServiceUnavailable) }
func Test_StaticRouteRegistration(t *testing.T) { runGalaTest(t, TestStaticRouteRegistration) }
func Test_StatusCodeValues(t *testing.T) { runGalaTest(t, TestStatusCodeValues) }
func Test_StreamResponse(t *testing.T) { runGalaTest(t, TestStreamResponse) }
func Test_StringResponse(t *testing.T) { runGalaTest(t, TestStringResponse) }
func Test_StringResponseWithCustomStatus(t *testing.T) { runGalaTest(t, TestStringResponseWithCustomStatus) }
func Test_Text(t *testing.T) { runGalaTest(t, TestText) }
func Test_TimeoutCreation(t *testing.T) { runGalaTest(t, TestTimeoutCreation) }
func Test_TooManyRequests(t *testing.T) { runGalaTest(t, TestTooManyRequests) }
func Test_TrailingSlashAddsSlash(t *testing.T) { runGalaTest(t, TestTrailingSlashAddsSlash) }
func Test_TrailingSlashCreation(t *testing.T) { runGalaTest(t, TestTrailingSlashCreation) }
func Test_TrailingSlashPreservesQuery(t *testing.T) { runGalaTest(t, TestTrailingSlashPreservesQuery) }
func Test_TrailingSlashSkipsExisting(t *testing.T) { runGalaTest(t, TestTrailingSlashSkipsExisting) }
func Test_TrailingSlashSkipsRoot(t *testing.T) { runGalaTest(t, TestTrailingSlashSkipsRoot) }
func Test_Unauthorized(t *testing.T) { runGalaTest(t, TestUnauthorized) }
func Test_UnprocessableEntity(t *testing.T) { runGalaTest(t, TestUnprocessableEntity) }
func Test_WWWRedirectAddsWWW(t *testing.T) { runGalaTest(t, TestWWWRedirectAddsWWW) }
func Test_WWWRedirectCreation(t *testing.T) { runGalaTest(t, TestWWWRedirectCreation) }
func Test_WWWRedirectSkipsWWW(t *testing.T) { runGalaTest(t, TestWWWRedirectSkipsWWW) }
func Test_WithBanner(t *testing.T) { runGalaTest(t, TestWithBanner) }
func Test_WithDebug(t *testing.T) { runGalaTest(t, TestWithDebug) }
func Test_WithErrorHandler(t *testing.T) { runGalaTest(t, TestWithErrorHandler) }
func Test_WithFilter(t *testing.T) { runGalaTest(t, TestWithFilter) }
func Test_WithName(t *testing.T) { runGalaTest(t, TestWithName) }
func Test_WithNotFoundHandler(t *testing.T) { runGalaTest(t, TestWithNotFoundHandler) }
func Test_WithPort(t *testing.T) { runGalaTest(t, TestWithPort) }
func Test_WithRoutes(t *testing.T) { runGalaTest(t, TestWithRoutes) }
func Test_WithShutdownTimeout(t *testing.T) { runGalaTest(t, TestWithShutdownTimeout) }
func Test_XMLBlobResponse(t *testing.T) { runGalaTest(t, TestXMLBlobResponse) }
func Test_XMLBlobWithStatusResponse(t *testing.T) { runGalaTest(t, TestXMLBlobWithStatusResponse) }
func Test_Xml(t *testing.T) { runGalaTest(t, TestXml) }
