// Code generated by GALA transpiler. DO NOT EDIT.

package server

import "fmt"
import "martianoff/gala/std"
import (
	. "martianoff/gala/test"
	. "martianoff/gala/collection_immutable"
	"github.com/martianoff/gala-server/httpcore"
	"time"
)

func buildReq(b *httpcore.TestRequestBuilder) Request {
	return Request{bridge: std.NewImmutable(b.Build())}
}
func testReq(method string, path string) *httpcore.TestRequestBuilder {
	return httpcore.NewTestRequestBuilder(method, path)
}
func TestNewServer(t T) T {
	var s = std.NewImmutable(NewServer())
	var t1 = std.NewImmutable(Eq(t, s.Get().RouteCount(), 0))
	var t2 = std.NewImmutable(Eq(t1.Get(), s.Get().Port, 8080))
	var t3 = std.NewImmutable(Eq(t2.Get(), s.Get().Name, "GALA Server"))
	var t4 = std.NewImmutable(Eq(t3.Get(), s.Get().FilterCount(), 0))
	return IsFalse(t4.Get(), s.Get().Debug)
}
func TestWithPort(t T) T {
	var s = std.NewImmutable(NewServer().WithPort(9090))
	return Eq(t, s.Get().Port, 9090)
}
func TestWithName(t T) T {
	var s = std.NewImmutable(NewServer().WithName("My API"))
	return Eq(t, s.Get().Name, "My API")
}
func TestWithDebug(t T) T {
	var s = std.NewImmutable(NewServer().WithDebug(true))
	return IsTrue(t, s.Get().Debug)
}
func TestWithBanner(t T) T {
	var s = std.NewImmutable(NewServer().WithBanner(false))
	return IsFalse(t, s.Get().Banner)
}
func TestConfigPreservedAcrossBuilderCalls(t T) T {
	var s = std.NewImmutable(NewServer().WithPort(3000).WithName("Test API").WithDebug(true).WithBanner(false).GET("/hello", func(req any) Response {
		return Ok("hello")
	}).WithFilter(Logger()))
	var t1 = std.NewImmutable(Eq(t, s.Get().Port, 3000))
	var t2 = std.NewImmutable(Eq(t1.Get(), s.Get().Name, "Test API"))
	var t3 = std.NewImmutable(IsTrue(t2.Get(), s.Get().Debug))
	var t4 = std.NewImmutable(IsFalse(t3.Get(), s.Get().Banner))
	var t5 = std.NewImmutable(Eq(t4.Get(), s.Get().RouteCount(), 1))
	return Eq(t5.Get(), s.Get().FilterCount(), 1)
}
func TestServerGET(t T) T {
	var s = std.NewImmutable(NewServer().GET("/hello", func(req any) Response {
		return Ok("hello")
	}))
	return Eq(t, s.Get().RouteCount(), 1)
}
func TestServerMultipleRoutes(t T) T {
	var s = std.NewImmutable(NewServer().GET("/", func(req any) Response {
		return Ok("home")
	}).POST("/users", func(req any) Response {
		return Created("ok")
	}).DELETE("/users/{id}", func(req any) Response {
		return NoContent()
	}))
	return Eq(t, s.Get().RouteCount(), 3)
}
func TestServerAllMethods(t T) T {
	var s = std.NewImmutable(NewServer().GET("/get", func(req any) Response {
		return Ok("get")
	}).POST("/post", func(req any) Response {
		return Ok("post")
	}).PUT("/put", func(req any) Response {
		return Ok("put")
	}).DELETE("/del", func(req any) Response {
		return Ok("del")
	}).PATCH("/patch", func(req any) Response {
		return Ok("patch")
	}).HEAD("/head", func(req any) Response {
		return Ok("head")
	}).OPTIONS("/opts", func(req any) Response {
		return Ok("opts")
	}))
	return Eq(t, s.Get().RouteCount(), 7)
}
func TestServerImmutability(t T) T {
	var s1 = std.NewImmutable(NewServer().GET("/a", func(req any) Response {
		return Ok("a")
	}))
	var s2 = std.NewImmutable(s1.Get().GET("/b", func(req any) Response {
		return Ok("b")
	}))
	var t1 = std.NewImmutable(Eq(t, s1.Get().RouteCount(), 1))
	return Eq(t1.Get(), s2.Get().RouteCount(), 2)
}
func TestServerAnyMethod(t T) T {
	var s = std.NewImmutable(NewServer().Any("/wildcard", func(req any) Response {
		return Ok("any")
	}))
	return Eq(t, s.Get().RouteCount(), 7)
}
func TestWithShutdownTimeout(t T) T {
	var s = std.NewImmutable(NewServer().WithShutdownTimeout(10 * time.Second))
	return Eq(t, s.Get().ShutdownTimeout, 10*time.Second)
}
func TestWithNotFoundHandler(t T) T {
	var s = std.NewImmutable(NewServer().WithNotFound(func(req any) Response {
		return NotFound("custom 404")
	}))
	return IsTrue(t, s.Get().NotFoundHandler != nil)
}
func TestWithErrorHandler(t T) T {
	var s = std.NewImmutable(NewServer().WithErrorHandler(func(err any) Response {
		return InternalError("custom error")
	}))
	return IsTrue(t, s.Get().ErrorHandler != nil)
}
func TestServerRoutesDebug(t T) T {
	var s = std.NewImmutable(NewServer().GET("/hello", func(req any) Response {
		return Ok("hello")
	}).POST("/users", func(req any) Response {
		return Created("ok")
	}))
	var routes = std.NewImmutable(s.Get().Routes())
	var t1 = std.NewImmutable(Eq(t, routes.Get().Size(), 2))
	return t1.Get()
}
func TestStaticRouteRegistration(t T) T {
	var s = std.NewImmutable(NewServer().Static("/public/", "./static").Static("/assets/", "./assets").GET("/api/health", func(req any) Response {
		return Ok("ok")
	}))
	var t1 = std.NewImmutable(Eq(t, s.Get().RouteCount(), 1))
	return Eq(t1.Get(), s.Get().Statics.Size(), 2)
}
func TestOk(t T) T {
	var resp = std.NewImmutable(Ok("hello"))
	var t1 = std.NewImmutable(Eq(t, resp.Get().Code(), 200))
	return Eq(t1.Get(), resp.Get().Body.Get(), "hello")
}
func TestCreated(t T) T {
	var resp = std.NewImmutable(Created("created"))
	var t1 = std.NewImmutable(Eq(t, resp.Get().Code(), 201))
	return Eq(t1.Get(), resp.Get().Body.Get(), "created")
}
func TestAccepted(t T) T {
	var resp = std.NewImmutable(Accepted("accepted"))
	var t1 = std.NewImmutable(Eq(t, resp.Get().Code(), 202))
	return Eq(t1.Get(), resp.Get().Body.Get(), "accepted")
}
func TestNoContent(t T) T {
	var resp = std.NewImmutable(NoContent())
	var t1 = std.NewImmutable(Eq(t, resp.Get().Code(), 204))
	return Eq(t1.Get(), resp.Get().Body.Get(), "")
}
func TestBadRequest(t T) T {
	var resp = std.NewImmutable(BadRequest("invalid"))
	var t1 = std.NewImmutable(Eq(t, resp.Get().Code(), 400))
	return Eq(t1.Get(), resp.Get().Body.Get(), "invalid")
}
func TestUnauthorized(t T) T {
	var resp = std.NewImmutable(Unauthorized("no access"))
	var t1 = std.NewImmutable(Eq(t, resp.Get().Code(), 401))
	return Eq(t1.Get(), resp.Get().Body.Get(), "no access")
}
func TestForbidden(t T) T {
	var resp = std.NewImmutable(Forbidden("forbidden"))
	var t1 = std.NewImmutable(Eq(t, resp.Get().Code(), 403))
	return Eq(t1.Get(), resp.Get().Body.Get(), "forbidden")
}
func TestNotFound(t T) T {
	var resp = std.NewImmutable(NotFound("not found"))
	var t1 = std.NewImmutable(Eq(t, resp.Get().Code(), 404))
	return Eq(t1.Get(), resp.Get().Body.Get(), "not found")
}
func TestMethodNotAllowed(t T) T {
	var resp = std.NewImmutable(MethodNotAllowed())
	return Eq(t, resp.Get().Code(), 405)
}
func TestConflict(t T) T {
	var resp = std.NewImmutable(Conflict("conflict"))
	var t1 = std.NewImmutable(Eq(t, resp.Get().Code(), 409))
	return Eq(t1.Get(), resp.Get().Body.Get(), "conflict")
}
func TestUnprocessableEntity(t T) T {
	var resp = std.NewImmutable(UnprocessableEntity("unprocessable"))
	var t1 = std.NewImmutable(Eq(t, resp.Get().Code(), 422))
	return Eq(t1.Get(), resp.Get().Body.Get(), "unprocessable")
}
func TestTooManyRequests(t T) T {
	var resp = std.NewImmutable(TooManyRequests("rate limited"))
	var t1 = std.NewImmutable(Eq(t, resp.Get().Code(), 429))
	return Eq(t1.Get(), resp.Get().Body.Get(), "rate limited")
}
func TestInternalError(t T) T {
	var resp = std.NewImmutable(InternalError("server error"))
	var t1 = std.NewImmutable(Eq(t, resp.Get().Code(), 500))
	return Eq(t1.Get(), resp.Get().Body.Get(), "server error")
}
func TestServiceUnavailable(t T) T {
	var resp = std.NewImmutable(ServiceUnavailable("unavailable"))
	var t1 = std.NewImmutable(Eq(t, resp.Get().Code(), 503))
	return Eq(t1.Get(), resp.Get().Body.Get(), "unavailable")
}
func TestRequestTimeout(t T) T {
	var resp = std.NewImmutable(RequestTimeout())
	return Eq(t, resp.Get().Code(), 408)
}
func TestCustomStatusCode(t T) T {
	var resp = std.NewImmutable(NewResponse(StatusCustom{}.Apply(418)).WithBody("I'm a teapot"))
	var t1 = std.NewImmutable(Eq(t, resp.Get().Code(), 418))
	return Eq(t1.Get(), resp.Get().Body.Get(), "I'm a teapot")
}
func TestJsonResponse(t T) T {
	var resp = std.NewImmutable(JsonResponse("{\"key\": \"value\"}"))
	var t1 = std.NewImmutable(Eq(t, resp.Get().Code(), 200))
	var t2 = std.NewImmutable(Eq(t1.Get(), resp.Get().Body.Get(), "{\"key\": \"value\"}"))
	return Eq(t2.Get(), resp.Get().HeaderValue("Content-Type"), "application/json")
}
func TestText(t T) T {
	var resp = std.NewImmutable(Text("plain text"))
	var t1 = std.NewImmutable(Eq(t, resp.Get().Code(), 200))
	var t2 = std.NewImmutable(Eq(t1.Get(), resp.Get().Body.Get(), "plain text"))
	return Eq(t2.Get(), resp.Get().HeaderValue("Content-Type"), "text/plain")
}
func TestHtml(t T) T {
	var resp = std.NewImmutable(Html("<h1>Hello</h1>"))
	var t1 = std.NewImmutable(Eq(t, resp.Get().Code(), 200))
	var t2 = std.NewImmutable(Eq(t1.Get(), resp.Get().Body.Get(), "<h1>Hello</h1>"))
	return Eq(t2.Get(), resp.Get().HeaderValue("Content-Type"), "text/html")
}
func TestXml(t T) T {
	var resp = std.NewImmutable(Xml("<root/>"))
	var t1 = std.NewImmutable(Eq(t, resp.Get().Code(), 200))
	var t2 = std.NewImmutable(Eq(t1.Get(), resp.Get().Body.Get(), "<root/>"))
	return Eq(t2.Get(), resp.Get().HeaderValue("Content-Type"), "application/xml")
}
func TestJsonWithStatus(t T) T {
	var resp = std.NewImmutable(JsonWithStatus(StatusCreated{}.Apply(), "{\"id\": 1}"))
	var t1 = std.NewImmutable(Eq(t, resp.Get().Code(), 201))
	var t2 = std.NewImmutable(Eq(t1.Get(), resp.Get().Body.Get(), "{\"id\": 1}"))
	return Eq(t2.Get(), resp.Get().HeaderValue("Content-Type"), "application/json")
}
func TestRedirect(t T) T {
	var resp = std.NewImmutable(Redirect("/new-location"))
	var t1 = std.NewImmutable(Eq(t, resp.Get().Code(), 302))
	return Eq(t1.Get(), resp.Get().HeaderValue("Location"), "/new-location")
}
func TestRedirectPermanent(t T) T {
	var resp = std.NewImmutable(RedirectPermanent("/permanent"))
	var t1 = std.NewImmutable(Eq(t, resp.Get().Code(), 301))
	return Eq(t1.Get(), resp.Get().HeaderValue("Location"), "/permanent")
}
func TestResponseWithHeader(t T) T {
	var resp = std.NewImmutable(Ok("hello").WithHeader("X-Custom", "test").WithHeader("X-Another", "value"))
	var t1 = std.NewImmutable(Eq(t, resp.Get().HeaderValue("X-Custom"), "test"))
	return Eq(t1.Get(), resp.Get().HeaderValue("X-Another"), "value")
}
func TestResponseWithBody(t T) T {
	var resp = std.NewImmutable(NoContent().WithBody("new body"))
	return Eq(t, resp.Get().Body.Get(), "new body")
}
func TestResponseWithStatus(t T) T {
	var resp = std.NewImmutable(Ok("hello").WithStatus(StatusAccepted{}.Apply()))
	return Eq(t, resp.Get().Code(), 202)
}
func TestResponseImmutability(t T) T {
	var r1 = std.NewImmutable(Ok("hello"))
	var r2 = std.NewImmutable(r1.Get().WithHeader("X-Custom", "test"))
	var t1 = std.NewImmutable(Eq(t, r1.Get().HeaderValue("X-Custom"), ""))
	return Eq(t1.Get(), r2.Get().HeaderValue("X-Custom"), "test")
}
func TestResponseChaining(t T) T {
	var resp = std.NewImmutable(NewResponse(StatusOk{}.Apply()).WithBody("chained").WithHeader("X-A", "1").WithHeader("X-B", "2").WithStatus(StatusAccepted{}.Apply()))
	var t1 = std.NewImmutable(Eq(t, resp.Get().Code(), 202))
	var t2 = std.NewImmutable(Eq(t1.Get(), resp.Get().Body.Get(), "chained"))
	var t3 = std.NewImmutable(Eq(t2.Get(), resp.Get().HeaderValue("X-A"), "1"))
	return Eq(t3.Get(), resp.Get().HeaderValue("X-B"), "2")
}
func TestHeaderValueNotFound(t T) T {
	var resp = std.NewImmutable(Ok("hello"))
	return Eq(t, resp.Get().HeaderValue("X-Missing"), "")
}
func TestResponseSetCookie(t T) T {
	var resp = std.NewImmutable(Ok("hello").SetCookie("session", "abc123"))
	var t1 = std.NewImmutable(Eq(t, resp.Get().Cookies.Get().Size(), 1))
	var cookie = std.NewImmutable(resp.Get().Cookies.Get().Head())
	var t2 = std.NewImmutable(Eq(t1.Get(), cookie.Get().Name.Get(), "session"))
	var t3 = std.NewImmutable(Eq(t2.Get(), cookie.Get().Value.Get(), "abc123"))
	return Eq(t3.Get(), cookie.Get().Path.Get(), "/")
}
func TestResponseSetSecureCookie(t T) T {
	var resp = std.NewImmutable(Ok("hello").SetSecureCookie("token", "xyz", 3600))
	var cookie = std.NewImmutable(resp.Get().Cookies.Get().Head())
	var t1 = std.NewImmutable(Eq(t, cookie.Get().Name.Get(), "token"))
	var t2 = std.NewImmutable(Eq(t1.Get(), cookie.Get().Value.Get(), "xyz"))
	var t3 = std.NewImmutable(Eq(t2.Get(), cookie.Get().Path.Get(), "/"))
	var t4 = std.NewImmutable(Eq(t3.Get(), cookie.Get().MaxAge.Get(), 3600))
	var t5 = std.NewImmutable(IsTrue(t4.Get(), cookie.Get().Secure.Get()))
	var t6 = std.NewImmutable(IsTrue(t5.Get(), cookie.Get().HttpOnly.Get()))
	return Eq(t6.Get(), cookie.Get().SameSite.Get(), "Lax")
}
func TestResponseDeleteCookie(t T) T {
	var resp = std.NewImmutable(Ok("hello").DeleteCookie("session"))
	var cookie = std.NewImmutable(resp.Get().Cookies.Get().Head())
	var t1 = std.NewImmutable(Eq(t, cookie.Get().Name.Get(), "session"))
	var t2 = std.NewImmutable(Eq(t1.Get(), cookie.Get().Value.Get(), ""))
	return Eq(t2.Get(), cookie.Get().MaxAge.Get(), -1)
}
func TestResponseMultipleCookies(t T) T {
	var resp = std.NewImmutable(Ok("hello").SetCookie("a", "1").SetCookie("b", "2").SetCookie("c", "3"))
	return Eq(t, resp.Get().Cookies.Get().Size(), 3)
}
func TestCookieImmutability(t T) T {
	var r1 = std.NewImmutable(Ok("hello"))
	var r2 = std.NewImmutable(r1.Get().SetCookie("session", "abc"))
	var t1 = std.NewImmutable(Eq(t, r1.Get().Cookies.Get().Size(), 0))
	return Eq(t1.Get(), r2.Get().Cookies.Get().Size(), 1)
}
func TestMethodSealed(t T) T {
	var t1 = std.NewImmutable(Eq(t, GET{}.Apply().Name(), "GET"))
	var t2 = std.NewImmutable(Eq(t1.Get(), POST{}.Apply().Name(), "POST"))
	var t3 = std.NewImmutable(Eq(t2.Get(), PUT{}.Apply().Name(), "PUT"))
	var t4 = std.NewImmutable(Eq(t3.Get(), DELETE{}.Apply().Name(), "DELETE"))
	var t5 = std.NewImmutable(Eq(t4.Get(), PATCH{}.Apply().Name(), "PATCH"))
	var t6 = std.NewImmutable(Eq(t5.Get(), HEAD{}.Apply().Name(), "HEAD"))
	return Eq(t6.Get(), OPTIONS{}.Apply().Name(), "OPTIONS")
}
func TestStatusCodeValues(t T) T {
	var t1 = std.NewImmutable(Eq(t, StatusOk{}.Apply().Code(), 200))
	var t2 = std.NewImmutable(Eq(t1.Get(), StatusCreated{}.Apply().Code(), 201))
	var t3 = std.NewImmutable(Eq(t2.Get(), StatusAccepted{}.Apply().Code(), 202))
	var t4 = std.NewImmutable(Eq(t3.Get(), StatusNoContent{}.Apply().Code(), 204))
	var t5 = std.NewImmutable(Eq(t4.Get(), StatusBadRequest{}.Apply().Code(), 400))
	var t6 = std.NewImmutable(Eq(t5.Get(), StatusUnauthorized{}.Apply().Code(), 401))
	var t7 = std.NewImmutable(Eq(t6.Get(), StatusForbidden{}.Apply().Code(), 403))
	var t8 = std.NewImmutable(Eq(t7.Get(), StatusNotFound{}.Apply().Code(), 404))
	var t9 = std.NewImmutable(Eq(t8.Get(), StatusMethodNotAllowed{}.Apply().Code(), 405))
	var t10 = std.NewImmutable(Eq(t9.Get(), StatusConflict{}.Apply().Code(), 409))
	var t11 = std.NewImmutable(Eq(t10.Get(), StatusInternalError{}.Apply().Code(), 500))
	var t12 = std.NewImmutable(Eq(t11.Get(), StatusServiceUnavailable{}.Apply().Code(), 503))
	return Eq(t12.Get(), StatusCustom{}.Apply(418).Code(), 418)
}
func TestRequestMethod(t T) T {
	var req = std.NewImmutable(buildReq(testReq("GET", "/hello")))
	return Eq(t, req.Get().Method().Name(), "GET")
}
func TestRequestPath(t T) T {
	var req = std.NewImmutable(buildReq(testReq("GET", "/users/42")))
	return Eq(t, req.Get().Path(), "/users/42")
}
func TestRequestBody(t T) T {
	var req = std.NewImmutable(buildReq(testReq("POST", "/data").WithBody("payload")))
	return Eq(t, req.Get().Body(), "payload")
}
func TestRequestParam(t T) T {
	var req = std.NewImmutable(buildReq(testReq("GET", "/users/42").WithPathParam("id", "42")))
	var t1 = std.NewImmutable(IsSome(t, req.Get().Param("id")))
	var t2 = std.NewImmutable(Eq(t1.Get(), req.Get().Param("id").Get(), "42"))
	return IsNone(t2.Get(), req.Get().Param("missing"))
}
func TestRequestParamInt(t T) T {
	var req = std.NewImmutable(buildReq(testReq("GET", "/users/42").WithPathParam("id", "42")))
	var t1 = std.NewImmutable(IsSome(t, req.Get().ParamInt("id")))
	var t2 = std.NewImmutable(Eq(t1.Get(), req.Get().ParamInt("id").Get(), 42))
	return IsNone(t2.Get(), req.Get().ParamInt("missing"))
}
func TestRequestQueryParam(t T) T {
	var req = std.NewImmutable(buildReq(testReq("GET", "/search").WithRawQuery("q=gala&page=2")))
	var t1 = std.NewImmutable(Eq(t, req.Get().QueryParam("q").Get(), "gala"))
	var t2 = std.NewImmutable(Eq(t1.Get(), req.Get().QueryParam("page").Get(), "2"))
	return IsNone(t2.Get(), req.Get().QueryParam("missing"))
}
func TestRequestQueryParamDefault(t T) T {
	var req = std.NewImmutable(buildReq(testReq("GET", "/search").WithRawQuery("q=gala")))
	var t1 = std.NewImmutable(Eq(t, req.Get().QueryParamDefault("q", "none"), "gala"))
	return Eq(t1.Get(), req.Get().QueryParamDefault("missing", "default"), "default")
}
func TestRequestQueryParamInt(t T) T {
	var req = std.NewImmutable(buildReq(testReq("GET", "/page").WithRawQuery("page=5")))
	var t1 = std.NewImmutable(IsSome(t, req.Get().QueryParamInt("page")))
	return Eq(t1.Get(), req.Get().QueryParamInt("page").Get(), 5)
}
func TestRequestHeader(t T) T {
	var req = std.NewImmutable(buildReq(testReq("GET", "/").WithHeader("Authorization", "Bearer token123")))
	var t1 = std.NewImmutable(IsSome(t, req.Get().Header("Authorization")))
	var t2 = std.NewImmutable(Eq(t1.Get(), req.Get().Header("Authorization").Get(), "Bearer token123"))
	return IsNone(t2.Get(), req.Get().Header("Missing"))
}
func TestRequestContentType(t T) T {
	var req = std.NewImmutable(buildReq(testReq("POST", "/").WithHeader("Content-Type", "application/json")))
	return Eq(t, req.Get().ContentType().Get(), "application/json")
}
func TestRequestCookie(t T) T {
	var req = std.NewImmutable(buildReq(testReq("GET", "/").WithCookie("session", "abc123")))
	var t1 = std.NewImmutable(IsSome(t, req.Get().Cookie("session")))
	var t2 = std.NewImmutable(Eq(t1.Get(), req.Get().Cookie("session").Get(), "abc123"))
	return IsNone(t2.Get(), req.Get().Cookie("missing"))
}
func TestRequestFormValue(t T) T {
	var req = std.NewImmutable(buildReq(testReq("POST", "/").WithFormParam("username", "alice")))
	var t1 = std.NewImmutable(IsSome(t, req.Get().FormValue("username")))
	return Eq(t1.Get(), req.Get().FormValue("username").Get(), "alice")
}
func TestRequestHost(t T) T {
	var req = std.NewImmutable(buildReq(testReq("GET", "/").WithHost("example.com")))
	return Eq(t, req.Get().Host(), "example.com")
}
func TestRequestScheme(t T) T {
	var req = std.NewImmutable(buildReq(testReq("GET", "/").WithScheme("https")))
	return Eq(t, req.Get().Scheme(), "https")
}
func TestRequestIsTLS(t T) T {
	var req1 = std.NewImmutable(buildReq(testReq("GET", "/")))
	var req2 = std.NewImmutable(buildReq(testReq("GET", "/").WithTLS(true)))
	var t1 = std.NewImmutable(IsFalse(t, req1.Get().IsTLS()))
	return IsTrue(t1.Get(), req2.Get().IsTLS())
}
func TestRequestRealIP(t T) T {
	var req = std.NewImmutable(buildReq(testReq("GET", "/").WithHeader("X-Real-Ip", "10.0.0.1").WithRemoteAddr("192.168.1.1:5000")))
	return Eq(t, req.Get().RealIP(), "10.0.0.1")
}
func TestRequestRealIPFallback(t T) T {
	var req = std.NewImmutable(buildReq(testReq("GET", "/").WithRemoteAddr("192.168.1.1:5000")))
	return Eq(t, req.Get().RealIP(), "192.168.1.1")
}
func TestRequestCtxGetSet(t T) T {
	var req = std.NewImmutable(buildReq(testReq("GET", "/")))
	req.Get().CtxSet("user", "alice")
	return Eq(t, req.Get().CtxGet("user").Get(), "alice")
}
func TestRequestCtxGetMissing(t T) T {
	var req = std.NewImmutable(buildReq(testReq("GET", "/")))
	return IsNone(t, req.Get().CtxGet("missing"))
}
func TestWithFilter(t T) T {
	var s = std.NewImmutable(NewServer().GET("/", func(req any) Response {
		return Ok("hello")
	}).WithFilter(Logger()).WithFilter(Recovery()))
	var t1 = std.NewImmutable(Eq(t, s.Get().RouteCount(), 1))
	return Eq(t1.Get(), s.Get().FilterCount(), 2)
}
func TestFilterImmutability(t T) T {
	var s1 = std.NewImmutable(NewServer().GET("/a", func(req any) Response {
		return Ok("a")
	}))
	var s2 = std.NewImmutable(s1.Get().WithFilter(Logger()))
	var t1 = std.NewImmutable(Eq(t, s1.Get().FilterCount(), 0))
	return Eq(t1.Get(), s2.Get().FilterCount(), 1)
}
func TestLoggerCreation(t T) T {
	return IsTrue(t, Logger() != nil)
}
func TestRecoveryCreation(t T) T {
	return IsTrue(t, Recovery() != nil)
}
func TestCorsCreation(t T) T {
	return IsTrue(t, Cors() != nil)
}
func TestCorsWithOriginsCreation(t T) T {
	return IsTrue(t, CorsWithOrigins("https://example.com") != nil)
}
func TestCorsWithConfigCreation(t T) T {
	return IsTrue(t, CorsWithConfig("https://example.com", "GET, POST", "Content-Type", "86400") != nil)
}
func TestAuthCreation(t T) T {
	return IsTrue(t, Auth() != nil)
}
func TestAuthWithValidatorCreation(t T) T {
	return IsTrue(t, AuthWithValidator(func(h any) bool {
		return h == "valid"
	}) != nil)
}
func TestAuthBearerCreation(t T) T {
	return IsTrue(t, AuthBearer(func(token any) bool {
		return token == "valid"
	}) != nil)
}
func TestBasicAuthCreation(t T) T {
	return IsTrue(t, BasicAuth(func(u any, p any) bool {
		return u == "admin"
	}) != nil)
}
func TestKeyAuthCreation(t T) T {
	return IsTrue(t, KeyAuth("header:X-API-Key", func(k any) bool {
		return k == "secret"
	}) != nil)
}
func TestRateLimitCreation(t T) T {
	return IsTrue(t, RateLimit(100.0, 10.0) != nil)
}
func TestRateLimitPerIPCreation(t T) T {
	return IsTrue(t, RateLimitPerIP(100.0, 10.0) != nil)
}
func TestTimeoutCreation(t T) T {
	return IsTrue(t, Timeout(5*time.Second) != nil)
}
func TestGzipCreation(t T) T {
	return IsTrue(t, Gzip() != nil)
}
func TestRequestIdCreation(t T) T {
	return IsTrue(t, RequestId() != nil)
}
func TestSecureCreation(t T) T {
	return IsTrue(t, Secure() != nil)
}
func TestBodyLimitCreation(t T) T {
	return IsTrue(t, BodyLimit("2M") != nil)
}
func TestBodyLimitBytesCreation(t T) T {
	return IsTrue(t, BodyLimitBytes(1024) != nil)
}
func TestCSRFCreation(t T) T {
	return IsTrue(t, CSRF("secret-key") != nil)
}
func TestHTTPSRedirectCreation(t T) T {
	return IsTrue(t, HTTPSRedirect() != nil)
}
func TestWWWRedirectCreation(t T) T {
	return IsTrue(t, WWWRedirect() != nil)
}
func TestNonWWWRedirectCreation(t T) T {
	return IsTrue(t, NonWWWRedirect() != nil)
}
func TestTrailingSlashCreation(t T) T {
	return IsTrue(t, TrailingSlash() != nil)
}
func TestRemoveTrailingSlashCreation(t T) T {
	return IsTrue(t, RemoveTrailingSlash() != nil)
}
func TestRewriteCreation(t T) T {
	return IsTrue(t, Rewrite(ArrayOf(std.Tuple[string, string]{V1: std.NewImmutable("/old/*"), V2: std.NewImmutable("/new/$1")})) != nil)
}
func TestNewGroup(t T) T {
	var g = std.NewImmutable(NewGroup())
	var t1 = std.NewImmutable(Eq(t, g.Get().RouteCount(), 0))
	return Eq(t1.Get(), g.Get().FilterCount(), 0)
}
func TestWithRoutes(t T) T {
	var api = std.NewImmutable(NewGroup().GET("/users", func(req Request) Response {
		return Ok("users")
	}).POST("/users", func(req Request) Response {
		return Created("ok")
	}))
	var s = std.NewImmutable(NewServer().WithRoutes(api.Get()))
	return Eq(t, s.Get().RouteCount(), 2)
}
func TestGroup(t T) T {
	var api = std.NewImmutable(NewGroup().GET("/users", func(req Request) Response {
		return Ok("users")
	}).POST("/users", func(req Request) Response {
		return Created("ok")
	}))
	var s = std.NewImmutable(NewServer().Group("/api/v1", api.Get()))
	return Eq(t, s.Get().RouteCount(), 2)
}
func TestGroupPreservesExistingRoutes(t T) T {
	var api = std.NewImmutable(NewGroup().GET("/items", func(req Request) Response {
		return Ok("items")
	}))
	var s = std.NewImmutable(NewServer().GET("/health", func(req any) Response {
		return Ok("ok")
	}).Group("/api", api.Get()))
	return Eq(t, s.Get().RouteCount(), 2)
}
func TestGroupMultipleGroups(t T) T {
	var v1 = std.NewImmutable(NewGroup().GET("/users", func(req Request) Response {
		return Ok("v1")
	}))
	var v2 = std.NewImmutable(NewGroup().GET("/users", func(req Request) Response {
		return Ok("v2")
	}))
	var s = std.NewImmutable(NewServer().Group("/api/v1", v1.Get()).Group("/api/v2", v2.Get()))
	return Eq(t, s.Get().RouteCount(), 2)
}
func TestRouteFilter(t T) T {
	var s = std.NewImmutable(NewServer().GET("/public", func(req any) Response {
		return Ok("public")
	}).GET("/secret", func(req any) Response {
		return Ok("secret")
	}, Auth()))
	var t1 = std.NewImmutable(Eq(t, s.Get().RouteCount(), 2))
	return Eq(t1.Get(), s.Get().FilterCount(), 0)
}
func TestRouteMultipleFilters(t T) T {
	var s = std.NewImmutable(NewServer().GET("/admin", func(req any) Response {
		return Ok("admin")
	}, Auth(), Logger()))
	return Eq(t, s.Get().RouteCount(), 1)
}
func TestGroupFilters(t T) T {
	var api = std.NewImmutable(NewGroup().GET("/users", func(req Request) Response {
		return Ok("users")
	}).WithFilter(Auth()))
	var s = std.NewImmutable(NewServer().GET("/health", func(req any) Response {
		return Ok("ok")
	}).Group("/api", api.Get()).WithFilter(Logger()))
	var t1 = std.NewImmutable(Eq(t, s.Get().RouteCount(), 2))
	return Eq(t1.Get(), s.Get().FilterCount(), 1)
}
func TestGroupFiltersDoNotLeakToParent(t T) T {
	var api = std.NewImmutable(NewGroup().GET("/secret", func(req Request) Response {
		return Ok("secret")
	}).WithFilter(Auth()).WithFilter(Recovery()))
	var s = std.NewImmutable(NewServer().GET("/public", func(req any) Response {
		return Ok("public")
	}).Group("/api", api.Get()))
	return Eq(t, s.Get().FilterCount(), 0)
}
func TestNestedGroups(t T) T {
	var inner = std.NewImmutable(NewGroup().GET("/detail", func(req Request) Response {
		return Ok("detail")
	}))
	var outer = std.NewImmutable(NewGroup().GET("/list", func(req Request) Response {
		return Ok("list")
	}).Group("/nested", inner.Get()))
	var s = std.NewImmutable(NewServer().Group("/api", outer.Get()))
	return Eq(t, s.Get().RouteCount(), 2)
}
func TestHTTPErrorNewHTTPError(t T) T {
	var err = std.NewImmutable(NewHTTPError(StatusNotFound{}.Apply(), "user not found"))
	var t1 = std.NewImmutable(Eq(t, err.Get().Code(), 404))
	var t2 = std.NewImmutable(Eq(t1.Get(), err.Get().Msg(), "user not found"))
	return IsNil(t2.Get(), err.Get().Unwrap())
}
func TestHTTPErrorWithInternal(t T) T {
	var internalErr std.Immutable[error] = std.NewImmutable[error](nil)
	var err = std.NewImmutable(NewHTTPErrorWithInternal(StatusInternalError{}.Apply(), "db error", internalErr.Get()))
	var t1 = std.NewImmutable(Eq(t, err.Get().Code(), 500))
	return Eq(t1.Get(), err.Get().Msg(), "db error")
}
func TestHTTPErrorToResponse(t T) T {
	var err = std.NewImmutable(NewHTTPError(StatusBadRequest{}.Apply(), "invalid input"))
	var resp = std.NewImmutable(err.Get().ToResponse())
	var t1 = std.NewImmutable(Eq(t, resp.Get().Code(), 400))
	return Eq(t1.Get(), resp.Get().Body.Get(), "invalid input")
}
func TestHTTPErrorToJsonResponse(t T) T {
	var err = std.NewImmutable(NewHTTPError(StatusNotFound{}.Apply(), "not found"))
	var resp = std.NewImmutable(err.Get().ToJsonResponse())
	var t1 = std.NewImmutable(Eq(t, resp.Get().Code(), 404))
	var t2 = std.NewImmutable(Eq(t1.Get(), resp.Get().HeaderValue("Content-Type"), "application/json"))
	var t3 = std.NewImmutable(Contains(t2.Get(), resp.Get().Body.Get(), "\"error\""))
	return Contains(t3.Get(), resp.Get().Body.Get(), "not found")
}
func TestHTTPErrorString(t T) T {
	var err = std.NewImmutable(NewHTTPError(StatusNotFound{}.Apply(), "not found"))
	var s = std.NewImmutable(err.Get().Error())
	var t1 = std.NewImmutable(Contains(t, s.Get(), "404"))
	return Contains(t1.Get(), s.Get(), "not found")
}
func TestJSONPResponse(t T) T {
	var resp = std.NewImmutable(JSONP("callback", "{\"name\": \"gala\"}"))
	var t1 = std.NewImmutable(Eq(t, resp.Get().Code(), 200))
	var t2 = std.NewImmutable(Eq(t1.Get(), resp.Get().HeaderValue("Content-Type"), "application/javascript"))
	var t3 = std.NewImmutable(Contains(t2.Get(), resp.Get().Body.Get(), "callback"))
	return Contains(t3.Get(), resp.Get().Body.Get(), "{\"name\": \"gala\"}")
}
func TestJSONPWithStatusResponse(t T) T {
	var resp = std.NewImmutable(JSONPWithStatus(StatusCreated{}.Apply(), "cb", "{\"id\": 1}"))
	var t1 = std.NewImmutable(Eq(t, resp.Get().Code(), 201))
	return Contains(t1.Get(), resp.Get().Body.Get(), "cb")
}
func TestHTMLBlobResponse(t T) T {
	var resp = std.NewImmutable(HTMLBlob(httpcore.ToBytes("<h1>Hello</h1>")))
	var t1 = std.NewImmutable(Eq(t, resp.Get().Code(), 200))
	return Eq(t1.Get(), resp.Get().HeaderValue("Content-Type"), "text/html")
}
func TestJSONBlobResponse(t T) T {
	var resp = std.NewImmutable(JSONBlob(httpcore.ToBytes("{\"ok\": true}")))
	var t1 = std.NewImmutable(Eq(t, resp.Get().Code(), 200))
	return Eq(t1.Get(), resp.Get().HeaderValue("Content-Type"), "application/json")
}
func TestXMLBlobResponse(t T) T {
	var resp = std.NewImmutable(XMLBlob(httpcore.ToBytes("<root/>")))
	var t1 = std.NewImmutable(Eq(t, resp.Get().Code(), 200))
	return Eq(t1.Get(), resp.Get().HeaderValue("Content-Type"), "application/xml")
}
func TestHTMLBlobWithStatusResponse(t T) T {
	var resp = std.NewImmutable(HTMLBlobWithStatus(StatusCreated{}.Apply(), httpcore.ToBytes("<p>Created</p>")))
	return Eq(t, resp.Get().Code(), 201)
}
func TestJSONBlobWithStatusResponse(t T) T {
	var resp = std.NewImmutable(JSONBlobWithStatus(StatusAccepted{}.Apply(), httpcore.ToBytes("{\"queued\": true}")))
	return Eq(t, resp.Get().Code(), 202)
}
func TestXMLBlobWithStatusResponse(t T) T {
	var resp = std.NewImmutable(XMLBlobWithStatus(StatusOk{}.Apply(), httpcore.ToBytes("<data/>")))
	return Eq(t, resp.Get().Code(), 200)
}
func TestStringResponse(t T) T {
	var resp = std.NewImmutable(String(StatusOk{}.Apply(), "hello world"))
	var t1 = std.NewImmutable(Eq(t, resp.Get().Code(), 200))
	var t2 = std.NewImmutable(Eq(t1.Get(), resp.Get().Body.Get(), "hello world"))
	return Eq(t2.Get(), resp.Get().HeaderValue("Content-Type"), "text/plain")
}
func TestStringResponseWithCustomStatus(t T) T {
	var resp = std.NewImmutable(String(StatusCreated{}.Apply(), "created"))
	return Eq(t, resp.Get().Code(), 201)
}
func TestStreamResponse(t T) T {
	var resp = std.NewImmutable(Stream(StatusOk{}.Apply(), "text/event-stream", "data: hello\n\n"))
	var t1 = std.NewImmutable(Eq(t, resp.Get().Code(), 200))
	var t2 = std.NewImmutable(Eq(t1.Get(), resp.Get().HeaderValue("Content-Type"), "text/event-stream"))
	return Contains(t2.Get(), resp.Get().Body.Get(), "data: hello")
}
func TestServerNamed(t T) T {
	var s = std.NewImmutable(NewServer().GET("/users", func(req any) Response {
		return Ok("users")
	}).Named("user-list").GET("/users/{id}", func(req any) Response {
		return Ok("user")
	}).Named("user-detail"))
	return Eq(t, s.Get().RouteCount(), 2)
}
func TestServerURLGeneration(t T) T {
	var s = std.NewImmutable(NewServer().GET("/users", func(req any) Response {
		return Ok("users")
	}).Named("user-list").GET("/users/{id}", func(req any) Response {
		return Ok("user")
	}).Named("user-detail"))
	var t1 = std.NewImmutable(IsSome(t, s.Get().URL("user-list")))
	var t2 = std.NewImmutable(Eq(t1.Get(), s.Get().URL("user-list").Get(), "/users"))
	var t3 = std.NewImmutable(Eq(t2.Get(), s.Get().URL("user-detail", "id", "42").Get(), "/users/42"))
	return IsNone(t3.Get(), s.Get().URL("missing"))
}
func TestServerRenderWithoutRenderer(t T) T {
	var s = std.NewImmutable(NewServer())
	var resp = std.NewImmutable(s.Get().Render("template", nil))
	return Eq(t, resp.Get().Code(), 500)
}
func TestFullFrameworkConfiguration(t T) T {
	var api = std.NewImmutable(NewGroup().GET("/users", func(req Request) Response {
		return Ok("users")
	}).POST("/users", func(req Request) Response {
		return Created("ok")
	}).WithFilter(Auth()))
	var admin = std.NewImmutable(NewGroup().GET("/stats", func(req Request) Response {
		return Ok("stats")
	}).WithFilter(AuthBearer(func(token any) bool {
		return token == "admin"
	})))
	var s = std.NewImmutable(NewServer().WithName("Full API").WithPort(9090).WithShutdownTimeout(15*time.Second).WithDebug(true).WithBanner(false).WithErrorHandler(func(err any) Response {
		return JsonResponse(fmt.Sprintf("{\"error\": \"%v\"}", err))
	}).WithNotFound(func(req any) Response {
		return NotFound("custom 404")
	}).GET("/", func(req any) Response {
		return Ok("Hello, GALA!")
	}).GET("/health", func(req any) Response {
		return JsonResponse("{\"status\": \"ok\"}")
	}).Static("/public/", "./static").Group("/api/v1", api.Get()).Group("/admin", admin.Get()).WithFilter(Logger()).WithFilter(Recovery()).WithFilter(Cors()).WithFilter(RateLimit(1000.0, 100.0)).WithFilter(RequestId()))
	var t1 = std.NewImmutable(Eq(t, s.Get().Port, 9090))
	var t2 = std.NewImmutable(Eq(t1.Get(), s.Get().Name, "Full API"))
	var t3 = std.NewImmutable(IsTrue(t2.Get(), s.Get().Debug))
	var t4 = std.NewImmutable(IsFalse(t3.Get(), s.Get().Banner))
	var t5 = std.NewImmutable(Eq(t4.Get(), s.Get().RouteCount(), 5))
	return Eq(t5.Get(), s.Get().FilterCount(), 5)
}
func TestWithBasePath(t T) T {
	var s = std.NewImmutable(NewServer().WithBasePath("/api/v1"))
	return Eq(t, s.Get().BasePath, "/api/v1")
}
func TestBasePathDefault(t T) T {
	var s = std.NewImmutable(NewServer())
	return Eq(t, s.Get().BasePath, "")
}
func TestBasePathPreservedAcrossBuilderCalls(t T) T {
	var s = std.NewImmutable(NewServer().WithBasePath("/api/v1").WithPort(9090).GET("/users", func(req any) Response {
		return Ok("users")
	}))
	var t1 = std.NewImmutable(Eq(t, s.Get().BasePath, "/api/v1"))
	var t2 = std.NewImmutable(Eq(t1.Get(), s.Get().Port, 9090))
	return Eq(t2.Get(), s.Get().RouteCount(), 1)
}
func TestBasePathWithRoutes(t T) T {
	var s = std.NewImmutable(NewServer().WithBasePath("/api/v1").GET("/users", func(req any) Response {
		return Ok("users")
	}).POST("/items", func(req any) Response {
		return Created("ok")
	}))
	var routes = std.NewImmutable(s.Get().Routes())
	var t1 = std.NewImmutable(Eq(t, routes.Get().Size(), 2))
	return Eq(t1.Get(), s.Get().BasePath, "/api/v1")
}
func TestListenTLSExists(t T) T {
	var s = std.NewImmutable(NewServer().WithPort(8443))
	return Eq(t, s.Get().Port, 8443)
}
func TestWithHealthCheck(t T) T {
	var s = std.NewImmutable(NewServer().WithHealthCheck("/health"))
	return Eq(t, s.Get().RouteCount(), 1)
}
func TestWithHealthCheckMultiple(t T) T {
	var s = std.NewImmutable(NewServer().WithHealthCheck("/health").GET("/api", func(req any) Response {
		return Ok("api")
	}))
	return Eq(t, s.Get().RouteCount(), 2)
}
func TestWithReadiness(t T) T {
	var s = std.NewImmutable(NewServer().WithReadiness("/ready", func() bool {
		return true
	}))
	return Eq(t, s.Get().RouteCount(), 1)
}
func TestWithReadinessMultiple(t T) T {
	var s = std.NewImmutable(NewServer().WithReadiness("/ready", func() bool {
		return true
	}).GET("/api", func(req any) Response {
		return Ok("api")
	}))
	return Eq(t, s.Get().RouteCount(), 2)
}
func TestWithWarmup(t T) T {
	var warmedUp = false
	var s = std.NewImmutable(NewServer().WithWarmup(func() any {
		warmedUp = true
		return nil
	}))
	return IsTrue(t, s.Get().warmup.IsDefined())
}
func TestWithWarmupDefault(t T) T {
	var s = std.NewImmutable(NewServer())
	return IsTrue(t, s.Get().warmup.IsEmpty())
}
func TestWithErrorMapper(t T) T {
	var mapper = std.NewImmutable(func(err error) std.Option[Response] {
		return std.Some[Response]{}.Apply(BadRequest(fmt.Sprintf("mapped: %v", err)))
	})
	var s = std.NewImmutable(NewServer().WithErrorMapper(mapper.Get()))
	return IsTrue(t, s.Get().errorMapper.IsDefined())
}
func TestWithErrorMapperDefault(t T) T {
	var s = std.NewImmutable(NewServer())
	return IsTrue(t, s.Get().errorMapper.IsEmpty())
}
func TestStatusUnprocessableEntityCode(t T) T {
	return Eq(t, StatusUnprocessableEntity{}.Apply().Code(), 422)
}
func TestStatusTooManyRequestsCode(t T) T {
	return Eq(t, StatusTooManyRequests{}.Apply().Code(), 429)
}
func TestStatusRequestTimeoutCode(t T) T {
	return Eq(t, StatusRequestTimeout{}.Apply().Code(), 408)
}
func TestStatusBadGatewayCode(t T) T {
	return Eq(t, StatusBadGateway{}.Apply().Code(), 502)
}
func TestExtendedStatusCodeValues(t T) T {
	var t1 = std.NewImmutable(Eq(t, StatusUnprocessableEntity{}.Apply().Code(), 422))
	var t2 = std.NewImmutable(Eq(t1.Get(), StatusTooManyRequests{}.Apply().Code(), 429))
	var t3 = std.NewImmutable(Eq(t2.Get(), StatusRequestTimeout{}.Apply().Code(), 408))
	return Eq(t3.Get(), StatusBadGateway{}.Apply().Code(), 502)
}
func TestMethodCustom(t T) T {
	var m = std.NewImmutable(CUSTOM{}.Apply("PURGE"))
	return Eq(t, m.Get().Name(), "PURGE")
}
func TestMethodCustomArbitrary(t T) T {
	var m = std.NewImmutable(CUSTOM{}.Apply("LINK"))
	return Eq(t, m.Get().Name(), "LINK")
}
func TestToMethodUnknown(t T) T {
	var m = std.NewImmutable(toMethod("PURGE"))
	return Eq(t, m.Get().Name(), "PURGE")
}
func TestToMethodKnown(t T) T {
	var t1 = std.NewImmutable(Eq(t, toMethod("GET").Name(), "GET"))
	var t2 = std.NewImmutable(Eq(t1.Get(), toMethod("POST").Name(), "POST"))
	var t3 = std.NewImmutable(Eq(t2.Get(), toMethod("PUT").Name(), "PUT"))
	var t4 = std.NewImmutable(Eq(t3.Get(), toMethod("DELETE").Name(), "DELETE"))
	var t5 = std.NewImmutable(Eq(t4.Get(), toMethod("PATCH").Name(), "PATCH"))
	var t6 = std.NewImmutable(Eq(t5.Get(), toMethod("HEAD").Name(), "HEAD"))
	return Eq(t6.Get(), toMethod("OPTIONS").Name(), "OPTIONS")
}
func TestNegotiateJson(t T) T {
	var r = std.NewImmutable(buildReq(testReq("GET", "/").WithHeader("Accept", "application/json")))
	var resp = std.NewImmutable(Negotiate(r.Get(), func() Response {
		return JsonResponse("{\"ok\":true}")
	}, func() Response {
		return Html("<p>ok</p>")
	}, func() Response {
		return Text("ok")
	}))
	var t1 = std.NewImmutable(Eq(t, resp.Get().Code(), 200))
	return Eq(t1.Get(), resp.Get().HeaderValue("Content-Type"), "application/json")
}
func TestNegotiateHtml(t T) T {
	var r = std.NewImmutable(buildReq(testReq("GET", "/").WithHeader("Accept", "text/html")))
	var resp = std.NewImmutable(Negotiate(r.Get(), func() Response {
		return JsonResponse("{\"ok\":true}")
	}, func() Response {
		return Html("<p>ok</p>")
	}, func() Response {
		return Text("ok")
	}))
	var t1 = std.NewImmutable(Eq(t, resp.Get().Code(), 200))
	return Eq(t1.Get(), resp.Get().HeaderValue("Content-Type"), "text/html")
}
func TestNegotiateFallback(t T) T {
	var r = std.NewImmutable(buildReq(testReq("GET", "/").WithHeader("Accept", "text/plain")))
	var resp = std.NewImmutable(Negotiate(r.Get(), func() Response {
		return JsonResponse("{\"ok\":true}")
	}, func() Response {
		return Html("<p>ok</p>")
	}, func() Response {
		return Text("ok")
	}))
	var t1 = std.NewImmutable(Eq(t, resp.Get().Code(), 200))
	return Eq(t1.Get(), resp.Get().HeaderValue("Content-Type"), "text/plain")
}
func TestUnprocessableEntityConstructor(t T) T {
	var resp = std.NewImmutable(UnprocessableEntity("invalid"))
	var t1 = std.NewImmutable(Eq(t, resp.Get().Code(), 422))
	return Eq(t1.Get(), resp.Get().Body.Get(), "invalid")
}
func TestTooManyRequestsConstructor(t T) T {
	var resp = std.NewImmutable(TooManyRequests("slow down"))
	var t1 = std.NewImmutable(Eq(t, resp.Get().Code(), 429))
	return Eq(t1.Get(), resp.Get().Body.Get(), "slow down")
}
func TestRequestTimeoutConstructor(t T) T {
	var resp = std.NewImmutable(RequestTimeout())
	return Eq(t, resp.Get().Code(), 408)
}
func TestBadGatewayConstructor(t T) T {
	var resp = std.NewImmutable(BadGateway("upstream error"))
	var t1 = std.NewImmutable(Eq(t, resp.Get().Code(), 502))
	return Eq(t1.Get(), resp.Get().Body.Get(), "upstream error")
}
func TestResponseCopyWithHeader(t T) T {
	var r1 = std.NewImmutable(Ok("hello"))
	var r2 = std.NewImmutable(r1.Get().WithHeader("X-Test", "value"))
	var t1 = std.NewImmutable(Eq(t, r1.Get().HeaderValue("X-Test"), ""))
	return Eq(t1.Get(), r2.Get().HeaderValue("X-Test"), "value")
}
func TestResponseCopyWithBody(t T) T {
	var r1 = std.NewImmutable(Ok("original"))
	var r2 = std.NewImmutable(r1.Get().WithBody("updated"))
	var t1 = std.NewImmutable(Eq(t, r1.Get().Body.Get(), "original"))
	return Eq(t1.Get(), r2.Get().Body.Get(), "updated")
}
func TestResponseCopyWithStatus(t T) T {
	var r1 = std.NewImmutable(Ok("hello"))
	var r2 = std.NewImmutable(r1.Get().WithStatus(StatusNotFound{}.Apply()))
	var t1 = std.NewImmutable(Eq(t, r1.Get().Code(), 200))
	return Eq(t1.Get(), r2.Get().Code(), 404)
}
func TestResponseCopyChained(t T) T {
	var resp = std.NewImmutable(Ok("original").WithBody("updated").WithHeader("X-A", "1").WithStatus(StatusCreated{}.Apply()))
	var t1 = std.NewImmutable(Eq(t, resp.Get().Body.Get(), "updated"))
	var t2 = std.NewImmutable(Eq(t1.Get(), resp.Get().HeaderValue("X-A"), "1"))
	return Eq(t2.Get(), resp.Get().Code(), 201)
}

